name: Setup Node
description: Setup Node and tools

inputs:
  node-version:
    default: "20.x"
    description: "Node version"
runs:
  using: "composite"
  steps:
    # This hell is described here: https://github.com/actions/setup-node/issues/899
    - name: Enable Corepack before setting up Node
      run: |
        corepack enable
      shell: bash
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'yarn'
        cache-dependency-path: '**/yarn.lock'
    - shell: bash
      run: |
        node --version
        yarn plugin import version
        yarn --version
