name: Setup Node
description: Setup Node and tools

inputs:
  node-version:
    default: "20.x"
    description: "Node version"
runs:
  using: "composite"
  steps:
    # This hell is described here: https://github.com/actions/setup-node/issues/899
    - name: Enable Corepack before setting up Node
      run: |
        yarn --version
        npm uninstall -g yarn
        corepack enable
        echo "Corepack enabled"

      shell: bash
    - name: Install node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
    - name: Check versions
      shell: bash
      run: |
        yarn set version stable
        echo "Checking versions"
        node --version
        yarn --version
