name: Setup Node
description: Setup Node and tools

inputs:
  node-version:
    # 18 is the minimum supported
    default: "20.x"
    description: "Node version"
runs:
  using: "composite"
  steps:
    - name: Enable Corepack before setting up Node
      run: |
        corepack enable
      shell: bash
    - name: Install node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
    - name: Check versions
      shell: bash
      run: |
        node --version
        yarn --version
        yarn set version 4.1.1 --yarn-path
        yarn --version
        
        
        
        
