name: Setup Node
description: Setup Node and tools

inputs:
  node-version:
    default: "20.x"
    description: "Node version"
runs:
  using: "composite"
  steps:
    # This hell is described here: https://github.com/actions/setup-node/issues/899
    - name: Enable Corepack before setting up Node
      run: |
        yarn --version
        corepack enable
        echo "Corepack enabled"

      shell: bash
    - name: Install node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
    - name: Check versions
      shell: bash
      run: |
        echo "Checking versions"
        node --version
        yarn --version
        #yarn plugin import version
        rm -f ~/.yarn*
        yarn cache clean
        yarn set version stable --yarn-path
        yarn -v
        cd ragstack-ai-ts
        yarn set version $(yarn -v)
        cd ../ragstack-ai-ts-e2e-tests
        yarn set version $(yarn -v)
        
        
        
        
        
