# https://github.com/dorny/paths-filter
e2e_tests:
  - added|deleted|modified: "packages/ragstack-ai/**"
  - "./.github/actions/**"
  - "./.github/workflows/ci.yml"
  - "./.github/workflows/_run_e2e_tests.yml"
