# https://github.com/dorny/paths-filter
e2e_tests:
  - added|deleted|modified: "ragstack-ai-ts-e2e-tests/**"
  - "ragstack-ai-ts/package.json"
  - "./.github/actions/**"
  - "./.github/workflows/ci.yml"
  - "./.github/workflows/_run_e2e_tests.yml"
