name: CI - Unit tests
on:
  pull_request:
    paths-ignore:
      - "README.md"
    branches:
      - main

concurrency:
  group: ragstack-unit-tests-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: ./.github/actions/setup-node

      - name: Run unit tests
        run: |
          cd ragstack-ai-js
          yarn install --immutable
          yarn run test
