name: Release RAGStack package

on:
  push:
    tags:
      - "ragstack-ai-ts-*"

jobs:
  release:
    name: Release package
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: "Setup: Node"
        uses: ./.github/actions/setup-node

      - name: "Install"
        run: yarn
      - name: "Release package"
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd packages/ragstack-ai-ts
          yarn run release:publish

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
          prerelease: false

      - name: Compute release number
        id: release-number
        shell: bash
        run: |
          echo "release-number=$(echo ${{ github.ref }} | sed -e 's/refs\/tags\/ragstack-ai-ts-//')" >> $GITHUB_OUTPUT

      - name: Update API reference
        uses: ./.github/actions/deploy-api-reference
        with:
          ragstack-version: ${{ steps.release-number.outputs.release-number }}
