name: Release RAGStack CLI package

on:
  push:
    tags:
      - "ragstack-ai-cli-*"

jobs:
  release:
    name: Release package
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: "Setup: Node"
        uses: ./.github/actions/setup-node

      - name: "Install"
        run: yarn
      - name: "Release package"
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd packages/ragstack-ai-cli
          yarn run release:publish

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
          prerelease: false
